"use client";
import Head from "next/head";
import LocationSearchBar from "../components/LocationSearchBar.js";

export default function Home() {
  return (
    <>
      <Head>
        <title>Weather Application</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className="container position-absolute top-50 start-50 translate-middle">
        <div className="d-flex flex-column align-items-center">
          <h1 className="text-center m-3">Weather Forecast App</h1>
          <LocationSearchBar />
        </div>
      </div>
    </>
  );
}
